### ISSUE TITLE
Unlcear MostCopied And MostPasted Counts

### ISSUE THREAD

**Issue by viper3400** [viper3400/ClipBoard#6]
For me it's not really clear, how appereance of the items on the "frequent" list are calculated.

A ClipBoardRecord object has an PastedCount and a CopiedCount which is also persisted in the csv content list. 
- CopiedCount has to be incremented when a string is copied.
- PastedCount has to be incrementend when a string is pasted.

Functions should be refined, removed from MainForm and integrated into ClipBoardListController.

Therefore it should be clear, on which list an item appears. Should an item appear on just one list or should it appear more than one time. Example: Should an item, which appears on the save list also appear on the frequent list?

**Comment by MrCull** [comment]
Nice issue :-)
Yeah I was never sure about the "frequent" feature.
Sometimes I think it's useful. Other times I'm not so sure.
When they both have the same "count" the string appears only one. Which is probably ok.
Perhaps if the max frequent count was increased (to say 5 (but also made configurable)) then maybe this would make this feature more useful(?).

**Comment by viper3400** [comment]
I've refined the "frequent list" in my development branch, see 7555ccd3e79ad8aa8a2026bd3fdbd6174399e9ae.

To generate the frequent list I'll look no longer at the copied count of an item. I think it's a frequent usage of an item should not be defined by how often it is copied, but how often it has been pasted. 

Further, the copied count is increased much to often in current master branch. so that the calculation is a bit fuzzy anyhow  (as @MrCull  wrote in the comment before),

- Frequent items are items which are pasted the most
- Frequent items are evaluated from the recent list
- For now, the 10 most frequently pasted items are shown in the list
- For now, frequent items still appear in the recent list
- CopiedCount is not taken into consideration for frequent list

I will test this next week in order to get an impression of usability of this change.

The aspect of configurable settings I will consider in further development.

**Comment by MrCull** [comment]
Sounds good!

**Comment by viper3400** [comment]
@MrCull 

Changes are available for test in my develop branch with commit c7ec21ee2099010dbfeec04fe4eb9f3198d27942.

I also implemented a basic configuration, see the updated readme for further information: https://github.com/viper3400/ClipBoard/blob/develop/README.md

You may also use the build binaries: https://ci.appveyor.com/project/viper3400/clipboard/build/0.0.0.4/artifacts
